{"name": "test_register_valid_new_user", "status": "failed", "statusDetails": {"message": "AssertionError:  FAIL FAIL FAIL\nassert 1 == 2", "trace": "self = <test_register_new_user.TestRegisterNewUser object at 0x0000020E562C2F20>\n\n    @pytest.mark.tcid13\n    def test_register_valid_new_user(self):\n    \n        my_account_so = MyAccountSignedOut(self.driver)\n        my_account_si = MyAccountSignedIn(self.driver)\n        #goto my account\n        my_account_so.go_to_my_account()\n    \n        #fill in email and password and hit register\n        rand_email_pwd = generic_random_email_pwd()\n        my_account_so.input_reg_username(rand_email_pwd[\"email\"])\n        my_account_so.input_reg_password(rand_email_pwd[\"password\"])\n        my_account_so.click_register_button()\n>       assert 1 == 2, \" FAIL FAIL FAIL\"\nE       AssertionError:  FAIL FAIL FAIL\nE       assert 1 == 2\n\npython_sel_frameworkproject\\tests\\my_account\\test_register_new_user.py:23: AssertionError"}, "attachments": [{"name": "screeshot", "source": "84d04d1f-3df2-4b43-a1d2-6d2e770c15fb-attachment.png", "type": "image/png"}], "start": 1664364780449, "stop": 1664364791796, "uuid": "cc00343a-a625-4120-baea-9235a5491d45", "historyId": "b88d659de08128ea216a9b397ce81b82", "testCaseId": "0c1093a2f70af0eecd751aa51b1bc956", "fullName": "python_sel_frameworkproject.tests.my_account.test_register_new_user.TestRegisterNewUser#test_register_valid_new_user", "labels": [{"name": "tag", "value": "tcid13"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "python_sel_frameworkproject.tests.my_account"}, {"name": "suite", "value": "test_register_new_user"}, {"name": "subSuite", "value": "TestRegisterNewUser"}, {"name": "host", "value": "DESKTOP-GG4DDGM"}, {"name": "thread", "value": "10640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "python_sel_frameworkproject.tests.my_account.test_register_new_user"}]}